### ISSUE TITLE
The grover task will not run.

### ISSUE THREAD

**Issue by jamiejones85** [MarshallOfSound/grunt-grover#3]
The example config given in the Readme doesn't run as it is registered as a multiTask. There needs to be a target given.

**Comment by MarshallOfSound** [comment]
Fixed in master

**Comment by jamiejones85** [comment]
Don't suppose you could tag a release with the latest changes in? Thanks

**Comment by MarshallOfSound** [comment]
Tagged on npm a while back, just tagged on github now :)

**Comment by jamiejones85** [comment]
Great, thanks
